---
# vars file for deployer
docker_image_name: "{{ DOCKER_IMAGE_NAME }}"  # Passed from Jenkins
app_port: "{{ AppPort }}"  # Passed from Jenkins
container_name: "petclinic"
jfrog_url: "{{ JFrogURL }}"  # Passed from Jenkins