---
- name: Gather information about installed packages
  package_facts:

- name: Check if Docker is installed
  shell: dpkg -l | grep -i docker-ce
  register: docker_installed
  ignore_errors: true

- name: Install Docker prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  when: docker_installed.rc != 0  # Only add the repository if Docker is not installed

- name: Update apt package index
  apt:
    update_cache: yes
  when: docker_installed.rc != 0  # Only update if Docker is not installed

- name: Install Docker
  apt:
    name: docker-ce
    state: latest
  when: docker_installed.rc != 0  # Only install if Docker is not installed

- name: Start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes